site_name: Qatar Imputation Server
theme:
  name: readthedocs
  features:
    - navigation.instant
nav:
    - Home: index.md
    - Getting Started: gettingstarted.md
    - Data Preparation: dataprep.md
    - Reference Panels: refpanels.md
    - Pipeline Overview: pipeline.md
    - Security: security.md
    - Contact: contact.md
plugins:
  - search
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/qatarimputation
